const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const script=fs.readFileSync('assets/boat_edge_v177_latest_bridge.js','utf8');
const window={}, document={readyState:'loading',addEventListener:()=>{}};
vm.runInNewContext(script,{window,document,console});
const b=window.BoatEdgeV177;assert.ok(b);
const sha='a'.repeat(64),par='b'.repeat(64), key='20261009-01-03';
const g={results_seen:false,unlock:false,scoring:false,RESULT_UNLOCK_TOKEN:null};
const status={connected:true,predictions_ready:true,active_model_id:'V1.21.33-APPROVED',target_date:'2026-10-09',formalParentSha:par,guards:g};
const good={derived:{world_a:{tickets:[{combo:'1-2-3'}]},world_b:{tickets:[{combo:'2-1-3'}]}},meta:{schema_version:'boat-edge-formal-approved-overlay-v1',race_key:key,model_id:status.active_model_id,model_approved:true,formal_gate_pass:true,scope:'FORMAL_FRESH_APPROVED_PRE_RESULT',freeze_sha256:sha,prediction_sha256:sha,parent_sha256:par,guards:g}};
assert.equal(b.acceptRaw(good,key,status),true);
assert.equal(b.acceptNormalized({race_key:key,derived:good.derived,formal_meta:good.meta},status),true);
const reject=(patch)=>assert.equal(b.acceptRaw(good,key,{...status,...patch}),false);
reject({connected:false});reject({predictions_ready:false});reject({active_model_id:'V1.21.99'});reject({target_date:'2026-10-08'});
reject({guards:{...g,unlock:true}});reject({guards:{...g,results_seen:true}});reject({guards:{...g,scoring:true}});reject({guards:{...g,RESULT_UNLOCK_TOKEN:'notnull'}});
for(const [k,value] of [['formal_gate_pass',false],['model_approved',false],['model_id','DIFFERENT'],['scope','SITE_REFERENCE'],['freeze_sha256','broken'],['prediction_sha256','broken'],['parent_sha256',sha],['race_key','20261009-01-04']])assert.equal(b.acceptRaw({...good,meta:{...good.meta,[k]:value}},key,status),false);
assert.equal(b.acceptRaw({...good,meta:{...good.meta,guards:{...g,scoring:true}}},key,status),false);
assert.equal(b.acceptRaw({...good,derived:{world_a:{tickets:[{combo:'1-1-2'}]}}},key,status),false);
assert.equal(b.acceptRaw({...good,derived:{world_a:{tickets:[{combo:'1-2-3'},{combo:'1-2-3'}]}}},key,status),false);
assert.equal(b.acceptRaw({...good,derived:{world_a:{tickets:[]}}},key,status),false);
assert.equal(b.acceptRaw({derived:good.derived},key,status),false);
const html=fs.readFileSync('index.html','utf8');
assert.match(html,/BoatEdgeV177\?\.acceptRaw\?\.\(raw,raceKey,state\.formal\)/);
assert.match(html,/BoatEdgeV177\?\.acceptNormalized\?\.\(d,state\.formal\)/);
assert.equal((html.match(/boat_edge_v177_latest_bridge\.js\?v=177/g)||[]).length,1);
assert.match(html,/boat_edge_v175_payout_bands\.js\?v=175/);
assert.match(html,/await refreshFormalStatus\(\);\s*const overlay=await loadFormalOverlay\(race\.race_key\)/);
console.log('V177_APPROVAL_BRIDGE_TESTS_PASS');
