const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const win={},doc={readyState:'loading',addEventListener(){}};
vm.runInNewContext(fs.readFileSync('assets/boat_edge_v175_payout_bands.js','utf8'),{window:win,document:doc});
const v=win.BoatEdgeV175;assert.ok(v);
for(const [x,b] of [[9.9,'under10'],[10,'10to29'],[20,'10to29'],[29.9,'10to29'],[30,'30to49'],[49.9,'30to49'],[50,'50to99'],[99.9,'50to99'],[100,'over100']])assert.equal(v.band(x),b);
for(const x of [null,'',0,-1,'abc'])assert.equal(v.band(x),null);
const bets={hole:[{combo:'1-2-3'},{combo:'2-3-1'},{combo:'3-4-5'},{combo:'4-5-6'}]};
const odds={'1-2-3':10.1,'2-3-1':20,'3-4-5':51,'4-5-6':125};
const a=v.analyze('hole',bets,odds);
assert.equal(a.status,'ok');assert.equal(a.high,2);assert.equal(a.veryHigh,1);assert.equal(a.counts['10to29'],2);
assert.equal(v.analyze('hole',bets,{'1-2-3':11,'2-3-1':21,'3-4-5':22,'4-5-6':29}).high,0);
assert.equal(v.analyze('hole',bets,{}).status,'missing_odds');
assert.equal(v.analyze('hole',bets,odds,true).status,'settled');
assert.equal(v.analyze('hit',bets,odds).status,'missing_tickets');
const invalid=v.analyze('hole',{hole:[{combo:'1-1-2'},{combo:'1-2-3'},{combo:'1-2-3'}]},odds);
assert.equal(invalid.total,1);
const code=fs.readFileSync('assets/boat_edge_v108.js','utf8');
const html=fs.readFileSync('index.html','utf8');
assert.equal((code.match(/window\.BoatEdgeV175\?\.register\?\.\(/g)||[]).length,1);
assert.equal((html.match(/boat_edge_v175_payout_bands\.js\?v=175/g)||[]).length,1);
assert.match(html,/boat_edge_v174_confidence\.js\?v=174/);
console.log('V175_ODDS_BAND_CLASSIFICATION_AND_DISPLAY_HOOKS_PASS');
