/* Run in repo root after installer: node tests/boat_edge_v168_odds_behavior.js */
'use strict';
const fs=require('fs'), assert=require('assert');
const body=fs.readFileSync('assets/boat_edge_v108.js','utf8');
const a='const officialPay100=resultConfirmed?Number(result?.trifecta_payout_yen_per_100):NaN;';
const b='const conf=(resultConfirmed&&effectiveSnap?.modes?.[mode]?.confidence!=null)';
assert.equal(body.split(a).length-1,1,'missing fresh-v-final odds mapping');
assert.equal(body.split(b).length-1,1,'unknown mapping ending');
const mid=body.slice(body.indexOf(a),body.indexOf(b));
assert(mid.includes('const rows=baseRows.map(x=>'));
const numeric=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))||Number(v)<=0?null:Number(v);
const run=new Function('baseRows','resultConfirmed','result','officialResult','odds','be166OddsPrice',mid+'\nreturn rows;');
const frozen=[{combo:'1-3-5',odds:44.8,p:10.4,stake_yen:1100},{combo:'1-5-3',odds:77.8,p:10.2,stake_yen:1000}];
const freezeString=JSON.stringify(frozen);
const fresh={'1-3-5':34.3,'1-5-3':81.4};
let x=run(frozen,true,{trifecta_payout_yen_per_100:1350},'1-3-5',fresh,numeric);
assert.equal(x[0].odds,13.5,'winner must show confirmed final odds');
assert.equal(x[0].oddsBasis,'official_final');
assert.equal(x[1].odds,null,'nonwinner has no official final odds');
assert.equal(x[1].oddsBasis,'final_unavailable');
assert.equal(x[0].stake_yen,1100);
assert.equal(JSON.stringify(frozen),freezeString,'pre-race frozen rows must remain byte-identical');
x=run(frozen,false,null,null,fresh,numeric);
assert.equal(x[0].odds,34.3,'pre-race must use new validated odds even if frozen x.odds is set');
assert.equal(x[1].odds,81.4);
x=run(frozen,false,null,null,{},numeric);
assert.equal(x[0].odds,null,'stale source has been rejected upstream');
x=run(frozen,true,{trifecta_payout_yen_per_100:null},'1-3-5',fresh,numeric);
assert.equal(x[0].odds,null,'missing payout must not be imputed');
x=run(frozen,true,{trifecta_payout_yen_per_100:1350},null,fresh,numeric);
assert.equal(x[0].odds,null,'missing final combo must not be imputed');
console.log('V168 actual source behavioral tests PASS: winner final 13.5x, nonwinner hidden, live 34.3x, stale blank, no payout blank, frozen 1100yen unchanged');
